#define SETTINGVIEW_OFFSET 40

#define MA_MENU_TITLE 0
#define MA_MENU_CONTROLLER 1
#define MA_SUB_DETAIL_HEADER_LINE_COUNT 13
#define MA_SUB_DETAIL_TEXT_PER_LINE 18
#define MA_SUB_DETAIL_LINE_HEIGHT 23

#define MA_SCROLL_IMAGE_WIDTH 320
#define MA_SCROLL_IMAGE_HEIGHT 135

enum {
    DOU_TYPE_DO_WUO = 0,
    DOU_TYPE_DOU_SPACE ,
    DOU_TYPE_PEIKING_BASE,
    DOU_TYPE_MO_PHOTO,
    DOU_TYPE_ART029,
};
typedef NSUInteger MaDouViewType;
