#define SETTINGVIEW_OFFSET 40

#define MA_MENU_TITLE 0
#define MA_MENU_CONTROLLER 1
#define MA_SUB_DETAIL_HEADER_LINE_COUNT 13
#define MA_SUB_DETAIL_TEXT_PER_LINE 18
#define MA_SUB_DETAIL_LINE_HEIGHT 23

#define MA_SHADOW_VIEW_WIDE 20
#define MA_SHADOW_VIEW_HEIGHT 440
#define MA_TOOLBAR_HEIGHT 44

#define MA_PLAIN_VIEW_MINIMUM_FRAME_COUNT 5
#define MA_PLAIN_VIEW_FRAME_WIDE 320

#define ZOOM_VIEW_TAG 100



#define TEXT_CONTRENT_FOR_REPLACEMENT @"TEXT_CONTRENT_FOR_REPLACEMENT"


enum {
    DOU_TYPE_DO_WUO = 0,
    DOU_TYPE_DOU_SPACE ,
    DOU_TYPE_PEIKING_BASE,
    DOU_TYPE_MO_PHOTO,
    DOU_TYPE_ART029,
};
typedef NSUInteger MaDouViewType;
